name: Quality checks & release

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v13.0.0
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.23'
      - name: Install mdbook-mermaid
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: badboy/mdbook-mermaid
          tag: v0.12.6
      - name: Build
        run: mdbook build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-html
          path: book

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build, lint]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: built-html
          path: ./frc-programming
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frc-programming
