name: Quality checks & release

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v13.0.0
  
  release:
    name: Build & release
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.23'
      - name: Install mdbook-mermaid
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: badboy/mdbook-mermaid
          tag: v0.12.6
      - name: Build
        run: mdbook build
      - name: Package
        run: tar -czf frc-programming.tar.gz book
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            frc-programming.tar.gz
          name: ${{ github.sha }}
        if: github.ref == 'refs/heads/main'
